DROP TABLE SEQ_DIAGRAM IF EXISTS;
DROP TABLE MEMBER_SESSION IF EXISTS;
DROP TABLE MEMBER IF EXISTS;
DROP SEQUENCE SEQ_DIAGRAM_SEQ IF EXISTS;
DROP SEQUENCE MEMBER_SEQ IF EXISTS;

CREATE TABLE MEMBER (
    ID          NUMBER(19)     NOT NULL,
    USERNAME    VARCHAR2(50)   NOT NULL,
    PASSWORD    VARCHAR2(100)  NOT NULL,
    NAME        VARCHAR2(100)  NOT NULL,
    EMPLOYEE_NO VARCHAR2(50)   NOT NULL,
    CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (ID),
    CONSTRAINT UK_MEMBER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_MEMBER_EMPLOYEE_NO UNIQUE (EMPLOYEE_NO)
);

CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE MEMBER_SESSION (
    TOKEN_HASH VARCHAR2(64) NOT NULL,
    MEMBER_ID  NUMBER(19)   NOT NULL,
    CREATED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP    NOT NULL,
    CONSTRAINT PK_MEMBER_SESSION PRIMARY KEY (TOKEN_HASH),
    CONSTRAINT FK_SESSION_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID)
);

CREATE TABLE SEQ_DIAGRAM (
    ID           NUMBER(19)     NOT NULL,
    MEMBER_ID    NUMBER(19)     NOT NULL,
    TITLE        VARCHAR2(200)  NOT NULL,
    DESCRIPTION  VARCHAR2(2000),
    MERMAID_CODE CLOB           NOT NULL,
    LAST_PROMPT  VARCHAR2(4000),
    CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SEQ_DIAGRAM PRIMARY KEY (ID),
    CONSTRAINT FK_DIAGRAM_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID)
);

CREATE SEQUENCE SEQ_DIAGRAM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
