DROP TABLE SEQ_DIAGRAM IF EXISTS;
DROP SEQUENCE SEQ_DIAGRAM_SEQ IF EXISTS;

CREATE TABLE SEQ_DIAGRAM (
    ID           NUMBER(19)     NOT NULL,
    TITLE        VARCHAR2(200)  NOT NULL,
    DESCRIPTION  VARCHAR2(2000),
    MERMAID_CODE CLOB           NOT NULL,
    LAST_PROMPT  VARCHAR2(4000),
    CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_SEQ_DIAGRAM PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DIAGRAM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
